#pragma once


#define PROTO_ERROR_NONE                        0
#define PROTO_ERROR_CRC32_MISMATCH              1
#define PROTO_ERROR_INVALID_PACKET_TYPE         2
#define PROTO_ERROR_PACKET_TYPE_NOT_ALLOWED     3
#define PROTO_ERROR_CREATE_PACKET_FAILED        4
#define PROTO_ERROR_SERIALIZE_HEADER_FAILED     5
#define PROTO_ERROR_SERIALIZE_PACKET_FAILED     6
#define PROTO_ERROR_SERIALIZE_CHECK_FAILED      7
#define PROTO_ERROR_STREAM_OVERFLOW             8
#define PROTO_ERROR_STREAM_ABORTED              9
