name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/msbuild.yml
    
  tests:
    runs-on: ${{needs.build.outputs.RUNNER}}
    needs: build

    steps:
      - name: run tests
        working-directory: ${{env.GITHUB_WORKSPACE}}bin\Debug\
        run: tests.exe
